# Generated by Django 4.1.1 on 2022-10-03 05:41

from unicodedata import name
from django.db import migrations

def populate_status(apps, schemaditor):
    entries = {
        'published': 'A post that appears on the site (to all users).',
        'draft': 'A post that is being worked on and is not ready to be viewed by others.',
        'archived': 'A post that no longer appears on the site.'
    }                      #👇Name of app 👇Name of class
    Status = apps.get_model("posts", "Status") 
    for name, desc in entries.items():
        status_obj = Status(name=name, description=desc)
        status_obj.save()

class Migration(migrations.Migration):

    dependencies = [ 
        ("posts", "0002_status"),
    ]

    operations = [migrations.RunPython(populate_status)] # pulls form function we created above
